/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin. */

"use strict";var l=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var p=Object.prototype.hasOwnProperty;var c=(n,o)=>{for(var d in o)l(n,d,{get:o[d],enumerable:!0})},s=(n,o,d,t)=>{if(o&&typeof o=="object"||typeof o=="function")for(let a of i(o))!p.call(n,a)&&a!==d&&l(n,a,{get:()=>o[a],enumerable:!(t=r(o,a))||t.enumerable});return n};var f=n=>s(l({},"__esModule",{value:!0}),n);var g={};c(g,{default:()=>e});module.exports=f(g);var m=require("obsidian"),e=class extends m.Plugin{onload(){this.addCommand({id:"nothing-noop",name:"Do nothing (no-op)",callback:()=>{}})}};

/* nosourcemap */